Jfr profiling mappings
QuiltMC/quilt-mappings pull request #110
Opened 2022-03-03 00:31 UTC by ByMartrixx

2022-03-03 05:42 UTC, OroArmor approved these changes

2022-03-03 07:13 UTC, LambdAurora approved these changes

2022-03-03 12:17 UTC, wafflecoffee approved these changes

2022-03-03 17:48 UTC, NoComment1105 approved these changes

2022-03-03 22:08 UTC, supersaiyansubtlety requested changes

2022-03-03 22:08 UTC, supersaiyansubtlety commented on mappings/net/minecraft/util/profiling/jfr/JvmProfiler.mapping
> +		ARG 3 remoteAdress
```suggestion
		ARG 3 remoteAddress
```

2022-03-04 04:41 UTC, supersaiyansubtlety approved these changes

2022-03-09 22:28 UTC, merged