Blocks and Items
QuiltMC/quilt-mappings pull request #130
Opened 2022-03-16 21:28 UTC by OroArmor

Still need to work my way through the sculk gen logic

2022-03-17 08:47 UTC, NoComment1105 requested changes
Looking good so far, a couple of comments

2022-03-17 08:47 UTC, NoComment1105 commented on mappings/net/minecraft/block/AbstractLichenBlock.mapping
> +	METHOD m_uoihoidn getLichenGrowThing ()Lnet/minecraft/unmapped/C_twpgwpwn;
GrowThing?

2022-03-17 08:47 UTC, NoComment1105 commented on mappings/net/minecraft/block/C_eprlufrn.mapping
> +CLASS net/minecraft/unmapped/C_eprlufrn net/minecraft/block/C_eprlufrn
Why the empty un-named class?

2022-03-17 08:47 UTC, NoComment1105 commented on mappings/net/minecraft/block/C_uevszakc.mapping
> +CLASS net/minecraft/unmapped/C_uevszakc net/minecraft/block/C_uevszakc
Is the hashed name intentional?

2022-03-17 18:08 UTC, OroArmor commented on mappings/net/minecraft/block/AbstractLichenBlock.mapping
> +	METHOD m_uoihoidn getLichenGrowThing ()Lnet/minecraft/unmapped/C_twpgwpwn;
Wip name. As for the rest

2022-03-18 22:03 UTC, IotaBread commented on mappings/net/minecraft/block/AbstractLichenBlock.mapping
> +	METHOD m_khvcoyem openFaces (Lnet/minecraft/unmapped/C_txtbiemp;)Ljava/util/Set;
```suggestion
	METHOD m_khvcoyem getOpenFaces (Lnet/minecraft/unmapped/C_txtbiemp;)Ljava/util/Set;
```

2022-03-18 22:03 UTC, IotaBread commented on mappings/net/minecraft/block/ExperienceBlock.mapping
> +CLASS net/minecraft/unmapped/C_nrkgonet net/minecraft/block/ExperienceBlock
This sounds like the block is made out of experience

2022-03-18 22:03 UTC, IotaBread commented on mappings/net/minecraft/block/GlowLichenBlock.mapping
> +	FIELD f_fjlfksey lichenGrow Lnet/minecraft/unmapped/C_twpgwpwn;
```suggestion
	FIELD f_fjlfksey spreadBehavior Lnet/minecraft/unmapped/C_twpgwpwn;
```

2022-03-18 22:03 UTC, IotaBread commented on mappings/net/minecraft/block/MangroveLeavesBlock.mapping
> +	METHOD m_iojhiogk closeToOtherPropagule (Lnet/minecraft/unmapped/C_vdvbsyle;Lnet/minecraft/unmapped/C_hynzadkk;)Z
```suggestion
	METHOD m_iojhiogk isCloseToOtherPropagule (Lnet/minecraft/unmapped/C_vdvbsyle;Lnet/minecraft/unmapped/C_hynzadkk;)Z
```

2022-03-18 22:03 UTC, IotaBread commented on mappings/net/minecraft/block/LichenSpreadBehavior.mapping
> +	METHOD m_mamsfnxt spreadable (Lnet/minecraft/unmapped/C_vdvbsyle;Lnet/minecraft/unmapped/C_twpgwpwn$C_evcfujfb;Z)Ljava/util/Optional;
```suggestion
	METHOD m_mamsfnxt isSpreadable (Lnet/minecraft/unmapped/C_vdvbsyle;Lnet/minecraft/unmapped/C_twpgwpwn$C_evcfujfb;Z)Ljava/util/Optional;
```
?

2022-03-18 22:03 UTC, IotaBread commented on mappings/net/minecraft/block/SculkVeinBlock.mapping
> +	FIELD f_lhdhlpuz samePosLichenGrowBehavior Lnet/minecraft/unmapped/C_twpgwpwn;
```suggestion
	FIELD f_lhdhlpuz samePosLichenSpreadBehavior Lnet/minecraft/unmapped/C_twpgwpwn;
```

2022-03-18 22:03 UTC, IotaBread commented on mappings/net/minecraft/block/SculkVeinBlock.mapping
> +	METHOD m_pkzupcww getSamePosLichenGrowBehavior ()Lnet/minecraft/unmapped/C_twpgwpwn;
```suggestion
	METHOD m_pkzupcww getSamePosLichenSpreadBehavior ()Lnet/minecraft/unmapped/C_twpgwpwn;
```

2022-03-18 22:03 UTC, IotaBread commented on mappings/net/minecraft/block/sculk/SculkBehavior.mapping
> +		METHOD m_tvkgrthy shuffledDirections (Ljava/util/Random;)Ljava/util/List;
```suggestion
		METHOD m_tvkgrthy getShuffledDirections (Ljava/util/Random;)Ljava/util/List;
```

2022-03-18 22:03 UTC, IotaBread commented on mappings/net/minecraft/item/ItemStack.mapping
> +	METHOD m_sxworkis is (Lnet/minecraft/unmapped/C_cjzoxshv;)Z
How about `matches`?

2022-04-06 16:27 UTC, NoComment1105 approved these changes

2022-04-06 16:36 UTC, merged