items and blocks
QuiltMC/quilt-mappings pull request #178
Opened 2022-05-13 21:15 UTC by OroArmor

2022-05-13 21:29 UTC, NoComment1105 requested changes

2022-05-13 21:29 UTC, NoComment1105 commented on mappings/net/minecraft/block/dispenser/BoatDispenserBehavior.mapping
> +		ARG 1 tyoe
```suggestion
		ARG 1 type
```

2022-05-13 21:29 UTC, NoComment1105 commented on mappings/net/minecraft/item/CompassItem.mapping
> +	METHOD m_ucwcymfo getLoadstonePosition (Lnet/minecraft/unmapped/C_hhlwcnih;)Lnet/minecraft/unmapped/C_ovcqqyqp;
Is it not a lodestone?

2022-05-13 21:30 UTC, OroArmor commented on mappings/net/minecraft/item/CompassItem.mapping
> +	METHOD m_ucwcymfo getLoadstonePosition (Lnet/minecraft/unmapped/C_hhlwcnih;)Lnet/minecraft/unmapped/C_ovcqqyqp;
oops

2022-05-13 21:46 UTC, wafflecoffee approved these changes
Good once NC's comments are addressed

2022-05-13 22:06 UTC, NoahvdAa approved these changes
Other than nc's comments, looks good

2022-05-13 22:33 UTC, ByMartrixx approved these changes

2022-05-16 22:42 UTC, supersaiyansubtlety approved these changes

2022-05-18 16:08 UTC, OroArmor commented on mappings/net/minecraft/item/CompassItem.mapping
> +	METHOD m_ucwcymfo getLoadstonePosition (Lnet/minecraft/unmapped/C_hhlwcnih;)Lnet/minecraft/unmapped/C_ovcqqyqp;
```suggestion
	METHOD m_ucwcymfo getLodestonePosition (Lnet/minecraft/unmapped/C_hhlwcnih;)Lnet/minecraft/unmapped/C_ovcqqyqp;
```

2022-05-18 16:34 UTC, merged