Chat and some other network-related mappings
QuiltMC/quilt-mappings pull request #188
Opened 2022-05-26 02:31 UTC by ByMartrixx

Mostly chat and network-related mappings, with some extra stuff I mapped along the way. I didn't map the signing part of the new chat system, so if anyone wants to map it go ahead

2022-05-26 03:58 UTC, OroArmor approved these changes

2022-05-28 19:56 UTC, supersaiyansubtlety requested changes
`dataPack` vs. `datapack` is inconsistent. 
Some of the inconsistencies aren't part of this PR though, so I'm not sure if this is the place to change things.

2022-05-28 19:56 UTC, supersaiyansubtlety commented on mappings/net/minecraft/server/Services.mapping
> +		ARG 0 authenticationServicew
```suggestion
		ARG 0 authenticationService
```

2022-05-29 00:52 UTC, ByMartrixx commented
I'd say to open an issue about the inconsistency, or just pr a fix to change all of them to `dataPack`. I suspect there are many places with both `dataPack` and `datapack`

2022-05-29 05:55 UTC, supersaiyansubtlety approved these changes

2022-05-30 16:05 UTC, merged