Document NetworkEncryptionUtils
QuiltMC/quilt-mappings pull request #189
Opened 2022-05-26 03:10 UTC by ByMartrixx

Mostly a port from yarn

2022-05-26 03:58 UTC, OroArmor approved these changes

2022-05-28 19:38 UTC, supersaiyansubtlety requested changes
Inconsistent with `<thing>-encoded` vs. `<thing> encoded` but otherwise looks good.

2022-05-28 19:38 UTC, supersaiyansubtlety commented on mappings/net/minecraft/network/encryption/NetworkEncryptionUtils.mapping
> +		COMMENT by Base64 encoded PCKS #8 encoded key, followed by {@value #RSA_PRIVATE_KEY_FOOTER}.
```suggestion
		COMMENT by Base64 encoded PCKS #8-encoded key, followed by {@value #RSA_PRIVATE_KEY_FOOTER}.
```
for consistency

2022-05-28 19:38 UTC, supersaiyansubtlety commented on mappings/net/minecraft/network/encryption/NetworkEncryptionUtils.mapping
> +		COMMENT by Base64 encoded PCKS #8 encoded key, followed by {@value #RSA_PRIVATE_KEY_FOOTER}.
```suggestion
		COMMENT by Base64 encoded PCKS #8-encoded key, followed by {@value #RSA_PRIVATE_KEY_FOOTER}.
```
consistency

2022-05-28 19:38 UTC, supersaiyansubtlety commented on mappings/net/minecraft/network/encryption/NetworkEncryptionUtils.mapping
> +		COMMENT by Base64 encoded X.509 encoded key, followed by {@value #RSA_PUBLIC_KEY_FOOTER}.
```suggestion
		COMMENT by Base64 encoded X.509-encoded key, followed by {@value #RSA_PUBLIC_KEY_FOOTER}.
```
consistency

2022-05-28 19:38 UTC, supersaiyansubtlety commented on mappings/net/minecraft/network/encryption/NetworkEncryptionUtils.mapping
> +		COMMENT by Base64 encoded X.509 encoded key, followed by {@value #RSA_PUBLIC_KEY_FOOTER}.
```suggestion
		COMMENT by Base64 encoded X.509-encoded key, followed by {@value #RSA_PUBLIC_KEY_FOOTER}.
```

2022-05-29 05:59 UTC, supersaiyansubtlety approved these changes

2022-05-30 16:05 UTC, merged