Client option mappings
QuiltMC/quilt-mappings pull request #194
Opened 2022-06-02 02:48 UTC by ByMartrixx

Fixes #190 and #193

2022-06-02 02:49 UTC, OroArmor approved these changes

2022-06-04 17:16 UTC, wafflecoffee approved these changes

2022-06-04 19:14 UTC, LambdAurora requested changes

2022-06-04 19:14 UTC, LambdAurora commented on mappings/net/minecraft/client/option/OptionInstance.mapping
> +	METHOD m_snmuxvjl getValue ()Ljava/lang/Object;
```suggestion
	METHOD m_snmuxvjl get ()Ljava/lang/Object;
		COMMENT {@return the value of this option}
```

To fix the inconsistency between set and get, the fact it's the value is already pretty obvious.

2022-06-04 19:14 UTC, LambdAurora commented on mappings/net/minecraft/client/option/OptionInstance.mapping
> +CLASS net/minecraft/unmapped/C_vbibxkxv net/minecraft/client/option/OptionInstance
```suggestion
CLASS net/minecraft/unmapped/C_vbibxkxv net/minecraft/client/option/Option
	COMMENT Represents a typed option with getters and setters for use in GUIs.
	COMMENT
	COMMENT @param <T> the option's value type
```
Instance honestly doesn't add anything.
This class represents an option.

2022-06-04 19:36 UTC, LambdAurora approved these changes

2022-06-07 15:20 UTC, merged