Recipe mappings
QuiltMC/quilt-mappings pull request #254
Opened 2022-10-19 23:33 UTC by Platymemo

There is a pretty decent change here to consider:
`CraftingRecipeJsonfactory` -> `RecipeJsonFactory` so that the new class can be named `CraftingRecipeJsonFactory`
`RecipeJsonFactory` is the base for all recipe factories, while the new `CraftingRecipeJsonFactory` is the base for all the crafting recipes

2022-10-21 23:37 UTC, OroArmor approved these changes

2022-10-21 23:40 UTC, OroArmor requested changes

2022-10-21 23:40 UTC, OroArmor commented on mappings/net/minecraft/data/server/RecipesProvider.mapping
> +	METHOD m_eedufxdm offerhangingSignRecipe (Ljava/util/function/Consumer;Lnet/minecraft/unmapped/C_gmbqjnle;Lnet/minecraft/unmapped/C_gmbqjnle;)V
```suggestion
	METHOD m_eedufxdm offerHangingSignRecipe (Ljava/util/function/Consumer;Lnet/minecraft/unmapped/C_gmbqjnle;Lnet/minecraft/unmapped/C_gmbqjnle;)V
```

2022-10-23 15:51 UTC, ByMartrixx approved these changes

2022-10-26 10:17 UTC, NoComment1105 approved these changes

2022-11-05 00:17 UTC, ix0rai approved these changes

2022-11-13 20:41 UTC, OroArmor approved these changes

2022-11-14 04:09 UTC, supersaiyansubtlety approved these changes

2022-12-02 07:53 UTC, OroArmor commented
Are you able to maintain this PR, or should it be superseded?

2022-12-09 16:34 UTC, merged