Do many many mappings
QuiltMC/quilt-mappings pull request #270
Opened 2022-11-09 17:15 UTC by NoComment1105

I should not have started on a Tuesday

2022-11-11 00:33 UTC, ByMartrixx requested changes

2022-11-11 00:33 UTC, ByMartrixx commented on mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
> +	METHOD m_acsoyrbk updateWidgetNaration (Lnet/minecraft/unmapped/C_pofrkllk;)V
```suggestion
	METHOD m_acsoyrbk updateWidgetNarration (Lnet/minecraft/unmapped/C_pofrkllk;)V
```

2022-11-11 00:33 UTC, ByMartrixx commented on mappings/net/minecraft/client/gui/widget/CenteredStringWidget.mapping
> +	METHOD m_teyiceld color (I)Lnet/minecraft/unmapped/C_bauydsgb;
```suggestion
	METHOD m_teyiceld getColor (I)Lnet/minecraft/unmapped/C_bauydsgb;
```

2022-11-11 00:33 UTC, ByMartrixx commented on mappings/net/minecraft/client/gui/widget/CenteredStringWidget.mapping
> +CLASS net/minecraft/unmapped/C_bauydsgb net/minecraft/client/gui/widget/CenteredStringWidget
`CenteredTextWidget`?

2022-11-11 00:33 UTC, ByMartrixx commented on mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
> +	FIELD f_dzpdyfdx tooltipDelayMs I
```suggestion
	FIELD f_dzpdyfdx tooltipDelay I
```

2022-11-11 00:33 UTC, ByMartrixx commented on mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
> +	FIELD f_iwvrdmpf hoverOrFocusedStartTime J
```suggestion
	FIELD f_iwvrdmpf hoverOrFocusStartTime J
```
This can probably be changed to something more concise

2022-11-11 00:33 UTC, ByMartrixx commented on mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
> +		ARG 1 ms
```suggestion
	METHOD m_xuhmsncd setTooltipDelay (I)V
		ARG 1 delay
```

2022-11-11 00:33 UTC, ByMartrixx commented on mappings/net/minecraft/network/chat/MessageSignature.mapping
> +			ARG 1 siignatureCache
```suggestion
			ARG 1 signatureCache
```

2022-11-11 00:47 UTC, NoComment1105 commented
I know this PR is title many mappings, but i plan to make lots of PRs. This is the first of many and I will leave it in its current state, to make the review process easier

2022-11-14 03:37 UTC, supersaiyansubtlety requested changes

2022-11-14 03:37 UTC, supersaiyansubtlety commented on mappings/net/minecraft/network/chat/MessageSignature.mapping
> +	FIELD f_bpkdlana BYTES I
Having `BYTES` and `bytes` seems unnecessarily confusing. 
Is `BYTES` the size of the `bytes` array? If so maybe:
```suggestion
	FIELD f_bpkdlana NUM_BYTES I
```

2022-11-17 19:02 UTC, OroArmor approved these changes

2022-11-17 19:02 UTC, OroArmor commented on mappings/net/minecraft/util/math/MatrixUtil.mapping
> +	FIELD f_kqccjreh SS F
What are these?

2022-11-19 15:49 UTC, ix0rai commented on mappings/net/minecraft/world/level/redstone/NeighborUpdater.mapping
> +		ARG 4 pos2
better names for these parameters across this whole class would be ideal
"pos1" and "pos2" doesn't tell you what they do

2022-11-23 00:02 UTC, ix0rai commented
@NoComment1105 would you mind if I handled `C_rwmwglbe` (`NeighborUpdater`)?

2022-11-28 02:16 UTC, ByMartrixx commented on mappings/net/minecraft/util/math/MatrixUtil.mapping
> +		ARG 0 matrix4f
I don't think these names are really good... maybe you could use or adapt yarn's names for these methods?

2022-11-30 23:18 UTC, ix0rai commented
already-covered mappings that need to be removed from this pr:
- `NeighborUpdater`
- `InstantNeighborUpdater`
- `Tooltip`

2022-12-02 07:52 UTC, OroArmor commented
Are you able to maintain this PR, or should it be superseded?

2022-12-07 04:03 UTC, ix0rai commented
@NoComment1105 would you mind if I stole the `network/chat` classes from you? I'm really disliking the amount of mojmap in your versions

2022-12-08 03:44 UTC, ix0rai commented
all `network.chat` mappings are superceded by #305 (sorry)

2022-12-08 10:15 UTC, NoComment1105 commented
Closing as I haven't got much time to finish

2022-12-08 10:15 UTC, closed without merging