Registry Mappings
QuiltMC/quilt-mappings pull request #272
Opened 2022-11-09 20:27 UTC by NoComment1105

2022-11-09 20:41 UTC, OroArmor requested changes

2022-11-09 20:41 UTC, OroArmor commented on mappings/net/minecraft/util/registry/BuiltInRegistries.mapping
> +	METHOD m_mwsegmux bootStrap ()V
```suggestion
	METHOD m_mwsegmux bootstrap ()V
```

2022-11-09 20:41 UTC, OroArmor commented on mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
> +	METHOD m_xcyamnji allRegistriesLifecycle ()Lcom/mojang/serialization/Lifecycle;
```suggestion
	METHOD m_xcyamnji getLifecycleForAllRegistries ()Lcom/mojang/serialization/Lifecycle;
```

2022-11-09 20:41 UTC, OroArmor commented on mappings/net/minecraft/util/registry/HolderLookup.mapping
> +		METHOD m_vhaoljfo registryLifecycle ()Lcom/mojang/serialization/Lifecycle;
```suggestion
		METHOD m_vhaoljfo getRegistryLifecycle ()Lcom/mojang/serialization/Lifecycle;
```

2022-11-09 20:41 UTC, OroArmor commented on mappings/net/minecraft/util/registry/Registry.mapping
> +	METHOD m_aotfisde getLifeCycle ()Lcom/mojang/serialization/Lifecycle;
```suggestion
	METHOD m_aotfisde getLifecycle ()Lcom/mojang/serialization/Lifecycle;
```

2022-11-09 20:41 UTC, OroArmor commented on mappings/net/minecraft/util/registry/RegistryLoader.mapping
> +	METHOD m_nrmjckec loadregistryContents (Lnet/minecraft/unmapped/C_piadqmzm$C_raywzonl;Lnet/minecraft/unmapped/C_tmnrpasf;Lnet/minecraft/unmapped/C_xhhleach;Lnet/minecraft/unmapped/C_eexxncvi;Lcom/mo
```suggestion
	METHOD m_nrmjckec loadRegistryContents (Lnet/minecraft/unmapped/C_piadqmzm$C_raywzonl;Lnet/minecraft/unmapped/C_tmnrpasf;Lnet/minecraft/unmapped/C_xhhleach;Lnet/minecraft/unmapped/C_eexxncvi;Lcom/mojang/serialization/Decoder;Ljava/util/Map;)V
```

2022-11-09 20:44 UTC, NoComment1105 commented on mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
> +	METHOD m_xcyamnji allRegistriesLifecycle ()Lcom/mojang/serialization/Lifecycle;
Iirc this is a record

2022-11-09 20:47 UTC, OroArmor commented on mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
> +	METHOD m_xcyamnji allRegistriesLifecycle ()Lcom/mojang/serialization/Lifecycle;
its a default method on an interface

2022-11-09 20:47 UTC, NoComment1105 commented on mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
> +	METHOD m_xcyamnji allRegistriesLifecycle ()Lcom/mojang/serialization/Lifecycle;
Ah

2022-11-09 23:18 UTC, OroArmor commented on mappings/net/minecraft/util/registry/BuiltInRegistries.mapping
> +	FIELD f_idnjesqk identifier Lnet/minecraft/unmapped/C_ncpywfca;
```suggestion
	FIELD f_idnjesqk ROOT_REGISTRY_KEY Lnet/minecraft/unmapped/C_ncpywfca;
```

2022-11-10 20:32 UTC, OroArmor approved these changes

2022-11-10 20:34 UTC, LambdAurora approved these changes

2022-11-11 00:39 UTC, ByMartrixx approved these changes

2022-11-11 00:39 UTC, ByMartrixx commented on mappings/net/minecraft/util/registry/BuiltInRegistries.mapping
> +		ARG 1 identifier
```suggestion
		ARG 1 id
```

2022-11-11 00:39 UTC, ByMartrixx commented on mappings/net/minecraft/util/registry/BuiltInRegistries.mapping
> +		ARG 1 identifier
```suggestion
		ARG 1 id
```

2022-11-11 00:39 UTC, ByMartrixx commented on mappings/net/minecraft/util/registry/BuiltInRegistries.mapping
> +		ARG 1 identifier
```suggestion
		ARG 1 id
```

2022-11-11 00:39 UTC, ByMartrixx commented on mappings/net/minecraft/util/registry/BuiltInRegistries.mapping
> +		ARG 1 identifier
```suggestion
		ARG 1 id
```

2022-11-11 00:39 UTC, ByMartrixx commented on mappings/net/minecraft/util/registry/DefaultMappedRegistry.mapping
> +		ARG 1 identifier
```suggestion
	FIELD f_mxvnnuoz id Lnet/minecraft/unmapped/C_ncpywfca;
	FIELD f_zosutomx holderReference Lnet/minecraft/unmapped/C_cjzoxshv$C_rjzpeyec;
	METHOD <init> (Ljava/lang/String;Lnet/minecraft/unmapped/C_xhhleach;Lcom/mojang/serialization/Lifecycle;Z)V
		ARG 1 id
```

2022-11-11 00:39 UTC, ByMartrixx commented on mappings/net/minecraft/util/registry/Registries.mapping
> +	METHOD m_oinrvkni levelToLevelStem (Lnet/minecraft/unmapped/C_xhhleach;)Lnet/minecraft/unmapped/C_xhhleach;
Do we use level stem for these classes?

2022-11-11 00:39 UTC, ByMartrixx commented on mappings/net/minecraft/util/registry/Registries.mapping
> +		ARG 0 identifier
```suggestion
		ARG 0 id
```

2022-11-11 00:39 UTC, ByMartrixx commented on mappings/net/minecraft/util/registry/RegistryLoader.mapping
> +		ARG 0 identifier
```suggestion
		ARG 0 id
```

2022-11-11 00:39 UTC, ByMartrixx commented on mappings/net/minecraft/util/registry/ResourceFileNamespace.mapping
> +		ARG 1 identifier
```suggestion
		ARG 1 id
	METHOD m_gfkrsuzx findMatchingResources (Lnet/minecraft/unmapped/C_tmnrpasf;)Ljava/util/Map;
	METHOD m_gnnhrtlr (Lnet/minecraft/unmapped/C_ncpywfca;)Z
		ARG 1 id
	METHOD m_ixttgzkp (Lnet/minecraft/unmapped/C_ncpywfca;)Z
		ARG 1 id
	METHOD m_uxvlnvug wrapToFilePath (Lnet/minecraft/unmapped/C_ncpywfca;)Lnet/minecraft/unmapped/C_ncpywfca;
		ARG 1 id
```

2022-11-13 01:42 UTC, merged