map VariantProvider and clean up variant <-> type distinction
QuiltMC/quilt-mappings pull request #284
Opened 2022-11-22 23:42 UTC by ix0rai

the sequel to the sadly deceased #279 
this pr gives up on having a convention and simply accepts mojang's `variant` name, since the new interface-based structure makes it impossible to have a clear distinction between variants and types

2022-11-22 23:44 UTC, OroArmor approved these changes

2022-11-22 23:44 UTC, OroArmor commented
Should we also consider renaming the enums?

2022-11-22 23:47 UTC, ix0rai commented
of course; they slipped my mind in my haze of grief over my previous pr

2022-11-26 04:37 UTC, OroArmor requested changes
I would look for uses of BoatVariant and make sure they are changed from type

2022-11-26 04:39 UTC, ix0rai commented
good idea!
will take a look

2022-11-26 04:45 UTC, ix0rai commented
will be more thorough tomorrow; but I changed all the obvious ones

2022-11-27 18:53 UTC, supersaiyansubtlety approved these changes

2022-11-28 01:26 UTC, ix0rai commented
oh, note from tomorrow:
couldn't find any more; I did make a check

2022-11-28 20:31 UTC, OroArmor approved these changes

2022-11-29 16:44 UTC, merged