Updates dependencies
QuiltMC/quilt-mappings pull request #289
Opened 2022-11-28 23:17 UTC by OroArmor

Also makes it so we know what unpick values fail, only took 2 years :iea:

2022-11-28 23:53 UTC, EnnuiL requested changes
Just one little thing

2022-11-28 23:53 UTC, EnnuiL commented on buildSrc/src/main/java/quilt/internal/tasks/unpick/UnpickJarTask.java
> -        systemProperty("java.util.logging.config.file", getProject().file("unpick-logging.properties"));
The file can be safely removed now, we should do that

2022-11-29 00:26 UTC, EnnuiL approved these changes

2022-11-29 00:28 UTC, supersaiyansubtlety approved these changes

2022-11-29 03:17 UTC, ByMartrixx approved these changes

2022-11-30 02:29 UTC, ix0rai approved these changes

2022-12-01 03:42 UTC, merged