miscellaneous mappings, mostly dfu coverage
QuiltMC/quilt-mappings pull request #306
Opened 2022-12-08 03:42 UTC by ix0rai

mapping dfu is so calming

notes:
fixes a bad name, one fix was marked as a schema

2022-12-08 15:41 UTC, TibiNonEst requested changes

2022-12-08 15:41 UTC, TibiNonEst commented on mappings/net/minecraft/item/map/MapState.mapping
> +	FIELD f_fcobggon centerY I
This should be `centerZ` not `centerY`.

2022-12-08 22:51 UTC, ix0rai commented on mappings/net/minecraft/item/map/MapState.mapping
> +	FIELD f_fcobggon centerY I
my mistake, sorry!

2022-12-09 02:03 UTC, ByMartrixx approved these changes

2022-12-18 04:32 UTC, OroArmor approved these changes

2022-12-20 04:34 UTC, merged