1.19.4 random things
QuiltMC/quilt-mappings pull request #373
Opened 2023-02-24 03:55 UTC by ix0rai

me when I test enigma
just trying to improve coverage before 1.19.4

- maps a lot of random garbage
- completes mappings in the `text` package
- fixes a couple inconsistent names

2023-03-01 16:12 UTC, EnnuiL requested changes
Looks good! Just few things:

2023-03-01 16:12 UTC, EnnuiL commented on mappings/net/minecraft/block/DecoratedPotPatterns.mapping
> +	FIELD f_auhlbqrf POTTY_PATTERN_SKULL_NAME Ljava/lang/String;
Potty Pattern? :P
```suggestion
	FIELD f_auhlbqrf POTTERY_PATTERN_SKULL_NAME Ljava/lang/String;
```

2023-03-01 16:12 UTC, EnnuiL commented on mappings/net/minecraft/client/gui/DrawableHelper.mapping
> +	FIELD f_wwyjxrzh LIGHT_DIRT_BACKGROUND_TEXTURE Lnet/minecraft/unmapped/C_ncpywfca;
oh no; i was so confused by this name but then i realized: it's the actual name of the texture; i don't like it!

2023-03-01 16:12 UTC, EnnuiL commented on mappings/net/minecraft/block/DecoratedPotPatterns.mapping
> +	FIELD f_tssagzls SHARD_TO_PATTERN Ljava/util/Map;
hm, if i assume this is what it is, shouldn't it be:
```suggestion
	FIELD f_tssagzls PATTERNS_BY_SHARDS Ljava/util/Map;
```
in order to fit conventions?

2023-03-01 16:19 UTC, ix0rai commented on mappings/net/minecraft/block/DecoratedPotPatterns.mapping
> +	FIELD f_auhlbqrf POTTY_PATTERN_SKULL_NAME Ljava/lang/String;
:Isa:

2023-03-01 16:19 UTC, ix0rai commented on mappings/net/minecraft/block/DecoratedPotPatterns.mapping
> +	FIELD f_auhlbqrf POTTY_PATTERN_SKULL_NAME Ljava/lang/String;
oh my gosh I can't even spell iea

2023-03-01 16:35 UTC, EnnuiL approved these changes

2023-03-13 05:25 UTC, OroArmor approved these changes

2023-03-13 14:59 UTC, ix0rai commented
failing mapping can just be removed

2023-03-14 17:02 UTC, merged