Redstone related mappings and refactors
QuiltMC/quilt-mappings pull request #402
Opened 2023-03-31 01:28 UTC by SpaceWalkerRS

In terms of new mappings:
- `RedstonePowerView ` is an interface that extends `BlockView` and contains only methods for querying emitted and received redstone power. I went with the Yarn convention for names of these methods, even though they're a bit bulky, they're more consistent with all the redstone related names used elsewhere.

In terms of refactors:
- `AbstractRedstoneGateBlock` has been renamed to `RedstoneDiodeBlock` for a more accurate and concise name. Several methods in this class, as well as its subclasses `RepeaterBlock` and `ComparatorBlock`, have been renamed to better reflect whether they deal with input or output.
- `AbstractBlock#emitsRedstonePower` has been renamed to `isRedstonePowerSource` to make it less confusing.

2023-03-31 02:13 UTC, OroArmor approved these changes

2023-03-31 02:15 UTC, ix0rai approved these changes
all the javadoc is lovely!

2023-04-03 02:07 UTC, EnnuiL requested changes
hello! midnight ennui here; this looks good on a glance, but i do have nitpicks;
i'll review it properly tomorrow

2023-04-03 02:07 UTC, EnnuiL commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		COMMENT
```suggestion
```

2023-04-03 02:07 UTC, EnnuiL commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		COMMENT
```suggestion
```

2023-04-03 02:07 UTC, EnnuiL commented on mappings/net/minecraft/world/RedstonePowerView.mapping
> +		COMMENT
```suggestion
```

2023-04-03 02:07 UTC, EnnuiL commented on mappings/net/minecraft/world/RedstonePowerView.mapping
> +		COMMENT
```suggestion
```

2023-04-03 02:07 UTC, EnnuiL commented on mappings/net/minecraft/world/RedstonePowerView.mapping
> +		COMMENT
```suggestion
```

2023-04-03 02:07 UTC, EnnuiL commented on mappings/net/minecraft/world/RedstonePowerView.mapping
> +		COMMENT
```suggestion
```

2023-04-03 12:51 UTC, LambdAurora requested changes

2023-04-03 12:51 UTC, LambdAurora commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		COMMENT Returns the weak redstone power this block emits in the given direction.
```suggestion
		COMMENT {@return the weak redstone power this block emits in the given direction}
```

2023-04-03 12:51 UTC, LambdAurora commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		COMMENT Returns the strong redstone power this block emits in the given direction.
```suggestion
		COMMENT {@return the strong redstone power this block emits in the given direction}
```

2023-04-03 12:51 UTC, LambdAurora commented on mappings/net/minecraft/world/RedstonePowerView.mapping
> +		COMMENT Returns the redstone power emitted from the given position in the given direction.
```suggestion
		COMMENT {@return the redstone power emitted from the given position in the given direction}
```

2023-04-03 12:51 UTC, LambdAurora commented on mappings/net/minecraft/world/RedstonePowerView.mapping
> +		COMMENT Returns whether redstone power is emitted from the given position in the given direction.
```suggestion
		COMMENT {@return whether redstone power is emitted from the given position in the given direction}
```

2023-04-03 12:51 UTC, LambdAurora commented on mappings/net/minecraft/world/RedstonePowerView.mapping
> +		COMMENT Returns the redstone power the given position receives from neighboring blocks.
```suggestion
		COMMENT {@return the redstone power the given position receives from neighboring blocks}
```

2023-04-03 12:51 UTC, LambdAurora commented on mappings/net/minecraft/world/RedstonePowerView.mapping
> +		COMMENT Returns the strong redstone power the given position receives from neighboring blocks.
```suggestion
		COMMENT {@return the strong redstone power the given position receives from neighboring blocks}
```

2023-04-03 12:51 UTC, LambdAurora commented on mappings/net/minecraft/world/RedstonePowerView.mapping
> +		COMMENT Returns the strong redstone power emitted from the given position in the given direction.
```suggestion
		COMMENT {@return the strong redstone power emitted from the given position in the given direction}
```

2023-04-03 12:51 UTC, LambdAurora commented on mappings/net/minecraft/world/RedstonePowerView.mapping
> +		COMMENT Returns the filtered redstone power emitted from the given position in the given direction.
```suggestion
		COMMENT {@return the filtered redstone power emitted from the given position in the given direction}
```

2023-04-03 13:59 UTC, LambdAurora commented
It's `{@return ...}` not `{@returns ...}` (this is why the build is failing)

2023-04-03 14:19 UTC, SpaceWalkerRS commented
Woops! I'll push a quick fix.

2023-04-03 15:48 UTC, LambdAurora approved these changes

2023-04-03 19:45 UTC, EnnuiL approved these changes

2023-04-05 15:15 UTC, merged