all the latest block things
QuiltMC/quilt-mappings pull request #411
Opened 2023-04-23 22:07 UTC by ix0rai

thought we should get up to speed on this

2023-04-23 22:13 UTC, EnnuiL approved these changes
I approve of the progress so far!

2023-04-26 01:35 UTC, EnnuiL approved these changes

2023-04-26 01:35 UTC, EnnuiL commented on mappings/net/minecraft/block/RedstoneWireBlock.mapping
> +		ARG 0 positions
hm, i just realized that you can't really make a plural of `pos`; maybe `poses`, `posi`? :p
yeah, keep it as is

2023-04-29 18:13 UTC, EnnuiL requested changes

2023-04-29 18:13 UTC, EnnuiL commented on mappings/net/minecraft/block/PitcherCropBlock.mapping
> +	FIELD f_fnokzkbm BONEMEAL_AGE_INCREASE I
```suggestion
	FIELD f_fnokzkbm BONE_MEAL_AGE_INCREASE I
```

2023-04-29 18:13 UTC, EnnuiL commented on mappings/net/minecraft/block/TorchflowerCropBlock.mapping
> +	FIELD f_nexibmib BONEMEAL_AGE_INCREASE I
```suggestion
	FIELD f_nexibmib BONE_MEAL_AGE_INCREASE I
```

2023-04-30 02:24 UTC, EnnuiL approved these changes

2023-05-01 18:46 UTC, OroArmor approved these changes

2023-05-03 18:15 UTC, merged