complete `net.minecraft.client.render`
QuiltMC/quilt-mappings pull request #421
Opened 2023-05-11 01:50 UTC by ix0rai

2023-05-12 03:15 UTC, EnnuiL approved these changes

2023-05-13 01:59 UTC, EnnuiL requested changes

2023-05-13 01:59 UTC, EnnuiL commented on gradle/libs.versions.toml
> +enigma = "1.7.5"
oh, note: this PR should perhaps sync with the upstream, since we already did that update

2023-05-16 23:55 UTC, EnnuiL approved these changes

2023-05-18 19:58 UTC, supersaiyansubtlety requested changes

2023-05-18 19:58 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/render/entity/model/EntityModelPartNames.mapping
> +		COMMENT he key of a left mid-leg model part, whose value is {@value}.
```suggestion
		COMMENT The key of a left mid-leg model part, whose value is {@value}.
```

2023-05-19 20:32 UTC, supersaiyansubtlety approved these changes

2023-05-19 22:50 UTC, merged