Revise the Minecraft dictionary and <p> style decisions
QuiltMC/quilt-mappings pull request #439
Opened 2023-05-31 23:34 UTC by EnnuiL

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
i need to review this myself

2023-06-01 00:07 UTC, ix0rai commented
@EnnuiL I'd prefer if we split this into two, the <p> fixes make it very difficult to sort out the dictionary changes

2023-06-01 00:09 UTC, EnnuiL commented
> @EnnuiL I'd prefer if we split this into two, the \<p\> fixes make it very difficult to sort out the dictionary changes

heck

2023-06-01 00:11 UTC, ix0rai commented
I mean you can look at the commits but two prs would be cleaner :p

2023-06-02 04:34 UTC, EnnuiL commented
This is still a draft due to aaaaaaaa

2023-06-04 04:07 UTC, supersaiyansubtlety requested changes

2023-06-04 04:07 UTC, supersaiyansubtlety commented on mappings/net/minecraft/obfuscate/DontObfuscate.mapping
>  	COMMENT but other members in the same class may stay obfuscated.</li>
```suggestion
	COMMENT 	<li>The annotation itself is not obfuscated.</li>
	COMMENT 	<li>If a class is annotated, it is not obfuscated. It's not yet clear if its
	COMMENT members will always become deobfuscated as well.</li>
	COMMENT 	<li>If a member is annotated, it and its containing class is not obfuscated,
	COMMENT but other members in the same class may stay obfuscated.</li>
```

2023-08-11 21:25 UTC, EnnuiL commented
I'll close this PR due to the sheer unmaintainability of it; this might be need to be done in many PRs

2023-08-11 21:25 UTC, closed without merging

2023-08-12 02:08 UTC, ix0rai commented
that's what aurora has been doing for ages :p