mostly client mappings
QuiltMC/quilt-mappings pull request #469
Opened 2023-07-27 03:16 UTC by ix0rai

new mappings? in this economy?

discussion question: should we consider breaking up the "every block is in `net.minecraft.block`" convention for absolutely wild stuff like putting sign blocks in `net.minecraft.block.sign`?

2023-07-27 04:23 UTC, supersaiyansubtlety reviewed
> discussion question: should we consider breaking up the "every block is in net.minecraft.block" convention for absolutely wild stuff like putting sign blocks in net.minecraft.block.sign?

Sounds good to me.

2023-07-27 04:23 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/multiplayer/prediction/BlockStatePredictionManager.mapping
> +	FIELD f_hcvpxtyt sequence I
Is this `int` literally a sequence?
AFAICT it's more like a `sequenceIndex`: it dictates the order of a thing that's part of a sequence.

2023-07-27 04:23 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/util/telemetry/event/GameLoadTimesEvent.mapping
> +		ARG 2 timerCreator
```suggestion
		ARG 2 timerFactory
```
?

2023-07-27 04:23 UTC, supersaiyansubtlety commented on mappings/net/minecraft/util/SegmentedAnglePrecision.mapping
> +	FIELD f_mqmrqvqi degreeToAngle F
```suggestion
	FIELD f_mqmrqvqi degreesToAngle F
```
or is there some reason this and the following fields use the singlular `degree`?

2023-07-27 04:23 UTC, supersaiyansubtlety commented on mappings/net/minecraft/util/SegmentedAnglePrecision.mapping
> +	FIELD f_ponlgpot angleToDegree F
```suggestion
	FIELD f_ponlgpot angleToDegrees F
```

2023-07-28 17:18 UTC, ix0rai commented on mappings/net/minecraft/client/multiplayer/prediction/BlockStatePredictionManager.mapping
> +	FIELD f_hcvpxtyt sequence I
the `sequence` name goes all the way down to `blockChangeSequence` in `ServerPlayNetworkHandler` through a fair few fields and classes, so I'm not going to address it in this pr

I do see your point though, maybe make an issue?

2023-07-28 17:29 UTC, ix0rai commented
> > discussion question: should we consider breaking up the "every block is in net.minecraft.block" convention for absolutely wild stuff like putting sign blocks in net.minecraft.block.sign?
> 
> Sounds good to me.

this is now implemented!

2023-07-29 05:11 UTC, EnnuiL approved these changes

2023-07-29 05:12 UTC, supersaiyansubtlety approved these changes

2023-07-29 05:13 UTC, EnnuiL requested changes
wait oh right; Javadoc's mad at you for missing references; should be an easy fix :p

2023-08-01 01:29 UTC, supersaiyansubtlety approved these changes

2023-08-01 14:15 UTC, EnnuiL approved these changes

2023-08-03 02:33 UTC, merged