Networking mappings
QuiltMC/quilt-mappings pull request #483
Opened 2023-08-14 21:33 UTC by TheGlitch76

Not ready for review; just opening so other people know I'm working on this

2023-08-15 20:28 UTC, TheGlitch76 commented
This is ready for review now.

2023-08-15 21:49 UTC, ix0rai commented
javadoc error: 
```
/net/minecraft/client/network/ServerInfo.java:275: error: reference not found
    * net.minecraft.network.packet.s2c.play.ResourcePackS2CPacket server
```

2023-08-15 22:22 UTC, TheGlitch76 commented
love that it doesn't show up from `gradlew build`

2023-08-15 22:43 UTC, ix0rai requested changes

2023-08-15 22:43 UTC, ix0rai commented on mappings/net/minecraft/server/network/ServerChunkSender.mapping
> +		ARG 1 posLong
```suggestion
		ARG 1 pos
```
long positions are always just `pos`, we're kinda assuming that if you're touching chunk internals you know about long encoding for positions

2023-08-15 22:43 UTC, ix0rai commented on mappings/net/minecraft/network/listener/C2SPacketListener.mapping
> +CLASS net/minecraft/unmapped/C_lpmetgbe net/minecraft/network/listener/C2SPacketListener
This name is contradictory to existing names:
A matching class for `S2C` is named `ClientPacketListener`, solving the "we already have that just below it in the inheritance tree" problem by renaming the other class `ClientPacketListener` -> `ClientCommonPacketListener`. I'm open to criticism on this decision (it was mine) but I think this is the better choice.

2023-08-15 22:43 UTC, ix0rai commented
> love that it doesn't show up from `gradlew build`

`gradle build javadocJar` baybee

2023-08-15 23:11 UTC, supersaiyansubtlety requested changes

2023-08-15 23:11 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/network/AbstractClientNetworkHandler.mapping
> +	FIELD f_qcgabfsl CONNECTION_LOST_TEXT Lnet/minecraft/unmapped/C_rdaqiwdt;
```suggestion
	FIELD f_qcgabfsl CONNECTION_LOST Lnet/minecraft/unmapped/C_rdaqiwdt;
```

2023-08-15 23:11 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/network/AbstractClientNetworkHandler.mapping
> +	METHOD m_gmmwbpns preparePackPrompt (Lnet/minecraft/unmapped/C_rdaqiwdt;Lnet/minecraft/unmapped/C_rdaqiwdt;)Lnet/minecraft/unmapped/C_rdaqiwdt;
```suggestion
	METHOD m_gmmwbpns composePackPrompt (Lnet/minecraft/unmapped/C_rdaqiwdt;Lnet/minecraft/unmapped/C_rdaqiwdt;)Lnet/minecraft/unmapped/C_rdaqiwdt;
```
?
`compose` seems like a more appropriate verb for combining `Text`s.
I think `prepare` has implications that timing or future changes are important.

2023-08-15 23:11 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/network/AbstractClientNetworkHandler.mapping
> +		ARG 1 sentPrompt
```suggestion
		ARG 1 prompt
```
it hasn't been sent yet, and the value passed is a param named `prompt`

2023-08-15 23:11 UTC, supersaiyansubtlety commented on mappings/net/minecraft/network/ServerConfigurationPacketHandler.mapping
> +	FIELD f_dfyozhxh INVALID_PLAYER_DATA_TEXT Lnet/minecraft/unmapped/C_rdaqiwdt;
```suggestion
	FIELD f_dfyozhxh INVALID_PLAYER_DATA Lnet/minecraft/unmapped/C_rdaqiwdt;
```

2023-08-15 23:11 UTC, supersaiyansubtlety commented on mappings/net/minecraft/network/listener/AbstractServerPacketHandler.mapping
> +	FIELD f_akpbpalo TIMEOUT_TEXT Lnet/minecraft/unmapped/C_rdaqiwdt;
```suggestion
	FIELD f_akpbpalo TIMEOUT Lnet/minecraft/unmapped/C_rdaqiwdt;
```

2023-08-15 23:11 UTC, supersaiyansubtlety commented on mappings/net/minecraft/server/network/ServerLoginNetworkHandler.mapping
> +	FIELD f_qhjiabpa UNEXPECTED_RESPONSE_TEXT Lnet/minecraft/unmapped/C_rdaqiwdt;
```suggestion
	FIELD f_qhjiabpa UNEXPECTED_RESPONSE Lnet/minecraft/unmapped/C_rdaqiwdt;
```

2023-08-27 23:02 UTC, ix0rai commented
@TheGlitch76 can I polish this up for you, or would you like to come back to it?

2023-08-27 23:17 UTC, TheGlitch76 commented
Please do!

2023-09-01 01:11 UTC, supersaiyansubtlety approved these changes

2023-09-01 02:44 UTC, ix0rai approved these changes

2023-09-03 13:51 UTC, merged