Packet listener mappings
QuiltMC/quilt-mappings pull request #503
Opened 2023-10-02 23:09 UTC by IotaBread

2023-10-03 00:49 UTC, OroArmor approved these changes

2023-10-03 17:42 UTC, ix0rai approved these changes

2023-10-03 23:52 UTC, supersaiyansubtlety requested changes

2023-10-03 23:52 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/gui/hud/chat/ChatMessageTag.mapping
`_TEXT` prefixes go against conventions (https://github.com/QuiltMC/quilt-mappings/pull/464), the tags should have `_TAG` prefixes instead to avoid special casing

2023-10-03 23:52 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/network/ChatListener.mapping
> +	FIELD f_cmownyuw VALIDATION_ERROR_TEXT Lnet/minecraft/unmapped/C_rdaqiwdt;
```suggestion
	FIELD f_cmownyuw VALIDATION_ERROR Lnet/minecraft/unmapped/C_rdaqiwdt;
```

2023-10-03 23:52 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
> +	FIELD f_runyodpr hasSeenInsecureChatWarning Z
```suggestion
	FIELD f_runyodpr seenInsecureChatWarning Z
```

2023-10-04 00:04 UTC, supersaiyansubtlety approved these changes

2023-10-06 02:21 UTC, merged