Added getAirSpeedMultiplier mapping in AquaticMoveControl
QuiltMC/quilt-mappings pull request #509
Opened 2023-10-08 04:47 UTC by HyperPigeon

Added getAirSpeedMultiplier mapping for private static method in AquaticMoveControl.

2023-10-09 23:29 UTC, OroArmor approved these changes

2023-10-09 23:44 UTC, supersaiyansubtlety requested changes

2023-10-09 23:44 UTC, supersaiyansubtlety commented on mappings/net/minecraft/entity/ai/control/AquaticMoveControl.mapping
> +	METHOD m_rvgifltm getAirSpeedMultiplier (F)F
```suggestion
	METHOD m_rvgifltm calcAirSpeedMultiplier (F)F
```
I don't think we use `get` for either static methods or methods that take params. The only exceptions I've seen are for map-like access (`getEntityByRawId`).

2023-10-10 01:18 UTC, supersaiyansubtlety approved these changes

2023-10-10 02:26 UTC, ix0rai approved these changes

2023-10-17 03:01 UTC, merged