Some Allay and Warden related mappings.
QuiltMC/quilt-mappings pull request #513
Opened 2023-10-30 22:20 UTC by HyperPigeon

- Mapped fields in `WardenEntity ` inner class to `range` and `positionSource`.
- Mapped ImmutableList field in `AllayEntity` to `itemThrownPitches`.
- Mapped public static void method in `GiveItemsToTargetTask` to `throwItemStackToEntity`.

2023-10-30 22:23 UTC, supersaiyansubtlety requested changes

2023-10-30 22:23 UTC, supersaiyansubtlety commented on mappings/net/minecraft/entity/passive/AllayEntity.mapping
> +	FIELD f_jxnwapwy itemThrownPitches Lcom/google/common/collect/ImmutableList;
```suggestion
	FIELD f_jxnwapwy thrownItemPitches Lcom/google/common/collect/ImmutableList;
```
I think this is the more natural ordering

2023-10-30 22:26 UTC, supersaiyansubtlety approved these changes

2023-10-31 00:10 UTC, ix0rai approved these changes

2023-10-31 02:43 UTC, ix0rai requested changes
fixes for checkstyle!

2023-10-31 02:43 UTC, ix0rai commented on mappings/net/minecraft/entity/mob/warden/WardenEntity.mapping
> +		FIELD f_eudouoeu range I
```suggestion
		FIELD f_eudouoeu RANGE I
```

2023-10-31 02:43 UTC, ix0rai commented on mappings/net/minecraft/entity/passive/AllayEntity.mapping
> +	FIELD f_jxnwapwy thrownItemPitches Lcom/google/common/collect/ImmutableList;
```suggestion
	FIELD f_jxnwapwy THROWN_ITEM_PITCHES Lcom/google/common/collect/ImmutableList;
```

2023-11-02 16:49 UTC, ix0rai approved these changes

2023-11-04 18:39 UTC, merged