first looks into 1.20.4
QuiltMC/quilt-mappings pull request #516
Opened 2023-12-08 19:53 UTC by moehreag

These are just mostly the unmapped classes I quickly found names for.
- mostly new classes that are mostly related to new stuff

Things I'm not sure about:
- `BlockCodecs` should probably not be in the `block` package. Where should it go?

2023-12-08 20:19 UTC, eristhea commented
codec stuff goes in `util`

2023-12-08 20:41 UTC, Patbox commented
BlockCodecs isn't a correct name, as the bound regsistry uses id of `block_type` and that class populates it

2023-12-08 20:45 UTC, moehreag commented
> BlockCodecs isn't a correct name, as the bound regsistry uses id of `block_type` and that class populates it

Hmm... looking at the class again maybe `BlockTypeRegistry` would be a better name?

2023-12-08 20:46 UTC, OroArmor commented
`BlockTypes`, follows the `Blocks` naming scheme

2023-12-08 20:46 UTC, Patbox commented
It's not a registry either, the closest thing would be Blocks or Items class

2023-12-08 20:46 UTC, OroArmor commented
Also being in the `n.m.block` is the right package

2023-12-08 20:48 UTC, moehreag commented
> Also being in the `n.m.block` is the right package

alright!

2023-12-08 23:53 UTC, supersaiyansubtlety requested changes

2023-12-08 23:53 UTC, supersaiyansubtlety commented on mappings/net/minecraft/util/JavaOps.mapping
AFAICT QMap doesn't use `o` for objects unless it's for `equals(Ljava/lang/Object;)Z`, and I'm not sure about any of the single-letter names of these params (except `i`).
I think it could make sense to use them for primitives (and maybe `Object`s), but the convention should be made clear if so.

2023-12-08 23:53 UTC, supersaiyansubtlety commented on mappings/net/minecraft/util/JavaOps.mapping
> +		ARG 0 object
inconsistent with other `o` params

2023-12-08 23:53 UTC, supersaiyansubtlety commented on mappings/net/minecraft/util/JavaOps.mapping
> +		ARG 1 o
```suggestion
		ARG 1 o1
```

2023-12-08 23:53 UTC, supersaiyansubtlety commented on mappings/net/minecraft/util/JavaOps.mapping
> +		ARG 1 object
inconsistent

2023-12-08 23:53 UTC, supersaiyansubtlety commented on mappings/net/minecraft/util/JavaOps.mapping
> +		ARG 1 o
```suggestion
		ARG 1 o1
```

2023-12-08 23:53 UTC, supersaiyansubtlety commented on mappings/net/minecraft/util/JavaOps.mapping
> +		ARG 2 s
```suggestion
		ARG 2 string
```
`s` is used for short in other places, and I think if single letters are used, they should be for primitives (and maybe `Object`s)

2023-12-08 23:53 UTC, supersaiyansubtlety commented on mappings/net/minecraft/util/JavaOps.mapping
> +			ARG 1 o
```suggestion
			ARG 1 o1
```

2023-12-09 00:16 UTC, moehreag commented on mappings/net/minecraft/util/JavaOps.mapping
> AFAICT QMap doesn't use `o` for objects unless it's for `equals(Ljava/lang/Object;)Z`, and I'm not sure about any of the single-letter names of these params (except `i`). I think it could make sense to use them for primitives (and maybe `Object`s), but the convention should be made clear if so.

It is entirely possible that using `o` for object parameters is something I entirely made up and isn't used anywhere and mentioned in any conventions (except for `equals` methods)

2023-12-09 13:23 UTC, merged