Village mappings
QuiltMC/quilt-mappings pull request #525
Opened 2024-01-05 17:09 UTC by IotaBread

100%s `n.m.village`. Thanks to @ix0rai for mapping `TradeOffers`!

2024-01-05 23:09 UTC, supersaiyansubtlety requested changes

2024-01-05 23:09 UTC, supersaiyansubtlety commented on mappings/net/minecraft/village/VillagerGossips.mapping
> +		ARG 2 prevValue
```suggestion
		ARG 2 oldValue
```
old/new, prev/next

2024-01-06 00:07 UTC, supersaiyansubtlety approved these changes

2024-01-08 01:24 UTC, ix0rai approved these changes
I helped but I can review the rest :p

2024-01-11 15:53 UTC, merged