Armadillo, plus some entity and command mappings
QuiltMC/quilt-mappings pull request #532
Opened 2024-01-16 20:41 UTC by IotaBread

There are a few mappings left in `ArmadilloEntity` and `ArmadilloBrain` if someone wants to map them

2024-01-16 20:50 UTC, moehreag approved these changes
I can't find any obvious issues.

2024-01-16 20:52 UTC, IotaBread commented on mappings/net/minecraft/client/render/entity/model/ArmadilloEntityModel.mapping
> +	COMMENT <caption>Model parts of this model</caption>
These tables should be auto generated, at least partially

2024-01-16 22:06 UTC, supersaiyansubtlety requested changes

2024-01-16 22:06 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/render/entity/animation/ArmadilloEntityAnimations.mapping
Questions about animation fields in `<EntityType>EntityAnimations` classes:
1) when are verbs present progressive? the only vaguely intuitive thing I can think of is maybe they should present progressive be for loopable animations?
2) do we really need the `<ENTITY_TYPE>` prefix for all the fields?

2024-01-16 22:06 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/render/entity/animation/ArmadilloEntityAnimations.mapping
> +	FIELD f_tadvldpp ARMADILLO_SCARE Lnet/minecraft/unmapped/C_mnzbondw;
```suggestion
	FIELD f_tadvldpp ARMADILLO_SCARED Lnet/minecraft/unmapped/C_mnzbondw;
```
I assume it's a scared reaction rather than the armadillo scaring other things

2024-01-16 22:06 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/render/entity/model/EntityModelPartNames.mapping
These comments seem redundant like the ones in CommonColors

2024-01-16 22:06 UTC, supersaiyansubtlety commented on mappings/net/minecraft/entity/passive/ArmadilloEntity.mapping
> +	METHOD m_bnhlbtvq brushScute ()V
```suggestion
	METHOD m_bnhlbtvq onBrushed ()V
```
?
since the method isn't doing the brushing

2024-01-17 00:50 UTC, IotaBread commented on mappings/net/minecraft/client/render/entity/animation/ArmadilloEntityAnimations.mapping
1. I just named them according to the names from ArmadilloEntity$State
2. I'm not sure, I just checked another class and saw that it was using the prefix, so I followed that

2024-01-17 00:50 UTC, IotaBread commented on mappings/net/minecraft/client/render/entity/animation/ArmadilloEntityAnimations.mapping
> +	FIELD f_tadvldpp ARMADILLO_SCARE Lnet/minecraft/unmapped/C_mnzbondw;
Whoops

2024-01-17 00:50 UTC, IotaBread commented on mappings/net/minecraft/client/render/entity/model/EntityModelPartNames.mapping
I think last time we had the discussion we ended up not removing the docs, might be good to make a convention or something

2024-01-17 01:37 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/render/entity/animation/ArmadilloEntityAnimations.mapping
1. ah, it's derived from a string, got it
2. ok, I think I'll make PR to remove the prefix

2024-01-17 01:37 UTC, supersaiyansubtlety approved these changes

2024-01-17 04:01 UTC, ix0rai approved these changes
looks great!

2024-01-17 04:01 UTC, eristhea commented on mappings/net/minecraft/entity/passive/ArmadilloBrain.mapping
> +	FIELD f_lxnldxiz BREEDING_INGREDIENT Lnet/minecraft/unmapped/C_tcpsydrv;
love this name. it's silly but yeah that's probably what I'd settle on too :p

2024-01-17 18:12 UTC, merged