Random mappings
QuiltMC/quilt-mappings pull request #554
Opened 2024-02-27 14:05 UTC by anonymous123-code

- World properties
- Explosions
- Projectiles
- Breeze
- wind charge
- world properties

2024-02-27 14:32 UTC, supersaiyansubtlety requested changes

2024-02-27 14:32 UTC, supersaiyansubtlety commented on mappings/net/minecraft/entity/Entity.mapping
> +	METHOD m_psgotipc getDeflectionBehavior (Lnet/minecraft/unmapped/C_ltpsyvhj;)Lnet/minecraft/unmapped/C_jslwmoew;
#553 calls this `getProjectileDeflector`, I can't check source rn to see which I prefer

2024-02-27 14:32 UTC, supersaiyansubtlety commented on mappings/net/minecraft/entity/projectile/DeflectionBehavior.mapping
> +CLASS net/minecraft/unmapped/C_jslwmoew net/minecraft/entity/projectile/DeflectionBehavior
#553 calls this `ProjectileDeflector`

2024-02-27 14:32 UTC, supersaiyansubtlety commented on mappings/net/minecraft/world/explosion/Explosion.mapping
> +	METHOD m_opijfldo getCausingEntity (Lnet/minecraft/unmapped/C_astfners;)Lnet/minecraft/unmapped/C_usxaxydn;
`CausingEntity` is a little awkward, would `Owner` 0r `Igniter` make sense?

2024-02-27 14:39 UTC, supersaiyansubtlety commented on mappings/net/minecraft/entity/projectile/DeflectionBehavior.mapping
> +CLASS net/minecraft/unmapped/C_jslwmoew net/minecraft/entity/projectile/DeflectionBehavior
Given it has a `deflect` method, `ProjectileDeflector` seems more appropriate (but can't check source rn)

2024-02-27 15:09 UTC, anonymous123-code commented
This PR duplicates some stuff done in #553, Ill wait until that one gets merged before updating this

2024-03-17 04:06 UTC, ix0rai commented
@anonymous123-code #553 has been merged, feel free to finish up this PR!

2024-03-31 00:10 UTC, ix0rai commented
mostly superceded by various PRs

2024-03-31 00:10 UTC, closed without merging