More mappings
QuiltMC/quilt-mappings pull request #558
Opened 2024-03-09 02:21 UTC by pyrox0

Woohoo we love mapping!!!

2024-03-09 04:31 UTC, supersaiyansubtlety requested changes

2024-03-09 04:31 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/option/GameOptions.mapping
> +	FIELD f_nvenypzh MENU_BACKGROUND_BLURRINESS_DEFAULT_VALUE D
```suggestion
	FIELD f_nvenypzh DEFAULT_MENU_BACKGROUND_BLURRINESS D
```

2024-03-09 04:31 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/world/WorldCreator.mapping
> +	FIELD f_ymncqayj areCommandsAllowed Ljava/lang/Boolean;
```suggestion
	FIELD f_ymncqayj allowCommands Ljava/lang/Boolean;
```

2024-03-09 04:31 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/world/WorldCreator.mapping
> +		ARG 1 areCommandsAllowed
```suggestion
	METHOD m_ombzuznr setAllowCommands (Z)V
		ARG 1 allow
```

2024-03-09 04:31 UTC, supersaiyansubtlety commented on mappings/net/minecraft/command/argument/ItemPredicateReader.mapping
> +	FIELD f_purwidzp UNKNOWN_COMPONENT_ARGUMENT_ITEM Lcom/mojang/brigadier/exceptions/DynamicCommandExceptionType;
```suggestion
	FIELD f_gkzxymrz ITEM_COMPONENT_EXPECTED Lcom/mojang/brigadier/exceptions/SimpleCommandExceptionType;
	FIELD f_hhuqrouq ITEM_COMPONENT_MALFORMED Lcom/mojang/brigadier/exceptions/Dynamic2CommandExceptionType;
	FIELD f_klnzxkqr ITEM_COMPONENT_REPEATED Lcom/mojang/brigadier/exceptions/DynamicCommandExceptionType;
	FIELD f_peywtmdd ITEM_TAG_UNKNOWN Lcom/mojang/brigadier/exceptions/DynamicCommandExceptionType;
	FIELD f_purwidzp ITEM_COMPONENT_UNKNOWN Lcom/mojang/brigadier/exceptions/DynamicCommandExceptionType;
```

2024-03-09 04:31 UTC, supersaiyansubtlety commented on mappings/net/minecraft/command/argument/ItemPredicateReader.mapping
> +	FIELD f_wafqtzoh INVALID_ITEM_ARGUMENT_ID Lcom/mojang/brigadier/exceptions/DynamicCommandExceptionType;
```suggestion
	FIELD f_wafqtzoh ITEM_ID_INVALID Lcom/mojang/brigadier/exceptions/DynamicCommandExceptionType;
```

2024-03-09 04:31 UTC, supersaiyansubtlety commented on mappings/net/minecraft/command/argument/ItemSlotArgumentType.mapping
> +	FIELD f_opwacyge SINGLE_SLOT_ONLY_EXCEPTION Lcom/mojang/brigadier/exceptions/DynamicCommandExceptionType;
```suggestion
	FIELD f_opwacyge ONLY_SINGLE_ALLOWED Lcom/mojang/brigadier/exceptions/DynamicCommandExceptionType;
```
I don't think an `EXCEPTION` suffix is necessary here, but it does have a suffix it should be `EXCEPTION_TYPE`

2024-03-10 16:05 UTC, pyrox0 commented
All suggestions incorporated!

2024-03-10 17:04 UTC, supersaiyansubtlety approved these changes

2024-03-11 03:09 UTC, ix0rai requested changes

2024-03-11 03:09 UTC, ix0rai commented on mappings/net/minecraft/client/render/entity/model/WindChargeEntityModel.mapping
> +	FIELD f_pokzsptz wind_charge Lnet/minecraft/unmapped/C_rglqxnbw;
```suggestion
	FIELD f_pokzsptz windCharge Lnet/minecraft/unmapped/C_rglqxnbw;
```

2024-03-11 03:09 UTC, ix0rai commented on mappings/net/minecraft/network/codec/PacketEncoder.mapping
> +	METHOD encode write (Ljava/lang/Object;Ljava/lang/Object;)V
```suggestion
	METHOD encode (Ljava/lang/Object;Ljava/lang/Object;)V
```
mapped by #557 as `encode` (you can't name it encode due to an enigma bug that was fixed in 2.2.1)

2024-03-14 16:31 UTC, merged