More mappings
QuiltMC/quilt-mappings pull request #570
Opened 2024-03-29 16:03 UTC by pyrox0

Updates a bunch of stuff that got unmapped from 24w12a and 24w13a, plus datafixer, resource pack, structure, and network mappings.

2024-03-29 22:03 UTC, supersaiyansubtlety requested changes
looks good, just 1 typo

2024-03-29 22:03 UTC, supersaiyansubtlety commented on mappings/net/minecraft/advancement/criterion/RecipeCraftedCriterionTrigger.mapping
> +		METHOD m_zrhvqutd craftedCraftedItem (Lnet/minecraft/unmapped/C_ncpywfca;)Lnet/minecraft/unmapped/C_rzypsigz;
```suggestion
		METHOD m_zrhvqutd crafterCraftedItem (Lnet/minecraft/unmapped/C_ncpywfca;)Lnet/minecraft/unmapped/C_rzypsigz;
```

2024-03-29 22:10 UTC, pyrox0 commented on mappings/net/minecraft/advancement/criterion/RecipeCraftedCriterionTrigger.mapping
> +		METHOD m_zrhvqutd craftedCraftedItem (Lnet/minecraft/unmapped/C_ncpywfca;)Lnet/minecraft/unmapped/C_rzypsigz;
Fixed!

2024-03-29 22:12 UTC, supersaiyansubtlety approved these changes

2024-03-31 00:09 UTC, ix0rai approved these changes
lovely!

2024-04-02 00:26 UTC, merged