some mappings in `n/m/world`
QuiltMC/quilt-mappings pull request #574
Opened 2024-04-02 02:28 UTC by ix0rai

broke my git oops. here's the PR!
some uncontroversial names to begin my journey to 100%ing `world`

2024-04-02 03:04 UTC, supersaiyansubtlety requested changes

2024-04-02 03:04 UTC, supersaiyansubtlety commented on mappings/net/minecraft/item/ProjectileItem.mapping
> +	METHOD m_mruwcksw initialiseProjectile (Lnet/minecraft/unmapped/C_ltpsyvhj;DDDFF)V
```suggestion
	METHOD m_mruwcksw initializeProjectile (Lnet/minecraft/unmapped/C_ltpsyvhj;DDDFF)V
```

2024-04-02 03:04 UTC, supersaiyansubtlety commented on mappings/net/minecraft/item/ProjectileItem.mapping
> +			FIELD f_okxxxhyo overrideDispenseBehavior Ljava/util/OptionalInt;
```suggestion
			FIELD f_okxxxhyo overrideDispenseEvent Ljava/util/OptionalInt;
```

2024-04-02 03:04 UTC, supersaiyansubtlety commented on mappings/net/minecraft/item/ProjectileItem.mapping
> +			METHOD m_somgfudg overrideDispenseBehavior (I)Lnet/minecraft/unmapped/C_dokwmwgh$C_jscrvllj$C_ciqfsiao;
```suggestion
			METHOD m_somgfudg overrideDispenseEvent (I)Lnet/minecraft/unmapped/C_dokwmwgh$C_jscrvllj$C_ciqfsiao;
```

2024-04-02 03:06 UTC, ix0rai commented on mappings/net/minecraft/item/ProjectileItem.mapping
> +			METHOD m_somgfudg overrideDispenseBehavior (I)Lnet/minecraft/unmapped/C_dokwmwgh$C_jscrvllj$C_ciqfsiao;
not sure how that happened

2024-04-02 03:07 UTC, supersaiyansubtlety approved these changes

2024-04-03 04:49 UTC, pyrox0 approved these changes
Looks good to me once conflicts are fixed!

2024-04-03 14:08 UTC, merged