complete entity, particle, and sound
QuiltMC/quilt-mappings pull request #579
Opened 2024-04-14 02:11 UTC by ix0rai

very straightforward work

2024-04-14 02:27 UTC, supersaiyansubtlety requested changes

2024-04-14 02:27 UTC, supersaiyansubtlety commented on mappings/net/minecraft/entity/effect/InfestedStatusEffect.mapping
> +	FIELD f_ivvbwqfr spawnedCountFunction Ljava/util/function/ToIntFunction;
```suggestion
	FIELD f_ivvbwqfr spawnCountFunction Ljava/util/function/ToIntFunction;
```

2024-04-14 02:29 UTC, supersaiyansubtlety approved these changes

2024-04-19 20:12 UTC, OroArmor approved these changes

2024-04-21 20:18 UTC, merged