improve recipe mappings
QuiltMC/quilt-mappings pull request #590
Opened 2024-05-08 02:33 UTC by ix0rai

2024-05-29 03:01 UTC, supersaiyansubtlety requested changes

2024-05-29 03:01 UTC, supersaiyansubtlety commented on mappings/net/minecraft/recipe/RecipeGridAligner.mapping
> +		ARG 5 x
```suggestion
		ARG 4 x
		ARG 5 y
```
Swapped. Also noticed `RecipeAlternativesWidget.InputSlot`'s `x` and `y` are swapped when I was checking this.

2024-05-29 03:05 UTC, ix0rai commented on mappings/net/minecraft/recipe/RecipeGridAligner.mapping
> +		ARG 5 x
that's where I got the names, I'll fix this

2024-05-29 03:11 UTC, ix0rai commented on mappings/net/minecraft/recipe/RecipeGridAligner.mapping
> +		ARG 5 x
done!

2024-05-29 03:12 UTC, supersaiyansubtlety approved these changes

2024-05-29 03:13 UTC, supersaiyansubtlety commented
Is this supposed to still have the 'wip' label?

2024-05-29 03:18 UTC, ix0rai commented
no it is not!
that would explain the lack of reviews lol

2024-06-09 03:22 UTC, ix0rai commented
superceded by #593

2024-06-09 03:22 UTC, closed without merging