start mapping new enchantment system
QuiltMC/quilt-mappings pull request #598
Opened 2024-06-12 01:10 UTC by ix0rai

2024-07-05 03:52 UTC, supersaiyansubtlety requested changes

2024-07-05 03:52 UTC, supersaiyansubtlety commented on mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
> +	METHOD m_obijpcqw getRandomItemWith (Lnet/minecraft/unmapped/C_pscqxfcs;Lnet/minecraft/unmapped/C_usxaxydn;Ljava/util/function/Predicate;)Ljava/util/Optional;
```suggestion
	METHOD m_obijpcqw getContextForRandomEquipmentWith (Lnet/minecraft/unmapped/C_pscqxfcs;Lnet/minecraft/unmapped/C_usxaxydn;Ljava/util/function/Predicate;)Ljava/util/Optional;
```
verbose, I know
but `getRandomItemWith` makes it sound like an `Item` is returned, and doesn't mention equipment

2024-07-05 03:52 UTC, supersaiyansubtlety commented on mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
> +		ARG 2 attributeModifierConsumer
```suggestion
		ARG 2 applicator
```
?

2024-07-05 03:52 UTC, supersaiyansubtlety commented on mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
> +		ARG 2 attributeModifierConsumer
```suggestion
		ARG 2 applicator
```
?

2024-07-05 03:52 UTC, supersaiyansubtlety commented on mappings/net/minecraft/enchantment/effect/AllOf.mapping
I'd prefer something closer to loom's `AllOfEnchantmentEffects`.
`AllOf` begs the questions "What's an `AllOf`?", "All of what?"

2024-07-05 17:07 UTC, OroArmor approved these changes
I think the enchantment provider classes `C_dpsarzgt`, `C_swckftoh`, and `C_ycmdmexf` need mapping along with the providers classes: p (EnchantmentProviders): `C_fudougzs` and `C_hzfgfhbe`. This could be a seperate PR thought

2024-07-06 01:25 UTC, ix0rai commented on mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
> +	METHOD m_obijpcqw getRandomItemWith (Lnet/minecraft/unmapped/C_pscqxfcs;Lnet/minecraft/unmapped/C_usxaxydn;Ljava/util/function/Predicate;)Ljava/util/Optional;
fair, i can't really think of a better way to communicate everything

2024-07-06 01:29 UTC, ix0rai commented on mappings/net/minecraft/enchantment/effect/AllOf.mapping
to me the package answers quite a bit of that, i'm ok with `AllOfEffects` though

2024-07-06 01:30 UTC, ix0rai commented
> I think the enchantment provider classes `C_dpsarzgt`, `C_swckftoh`, and `C_ycmdmexf` need mapping along with the providers classes: p (EnchantmentProviders): `C_fudougzs` and `C_hzfgfhbe`. This could be a seperate PR thought

I'll map those in my next PR

2024-07-06 01:34 UTC, supersaiyansubtlety approved these changes

2024-07-09 01:37 UTC, merged