revive #600
QuiltMC/quilt-mappings pull request #604
Opened 2024-07-05 03:10 UTC by ix0rai

2024-07-05 03:13 UTC, ix0rai commented
all comments are addressed from the original PR. we can consider this to already have my approval

2024-07-05 04:03 UTC, supersaiyansubtlety approved these changes

2024-07-07 03:49 UTC, supersaiyansubtlety commented
re-reviewing because I found some issues when updating #607

2024-07-07 04:20 UTC, supersaiyansubtlety requested changes

2024-07-07 04:20 UTC, supersaiyansubtlety commented on mappings/net/minecraft/block/entity/BannerBlockEntity.mapping
> +	FIELD f_yqkmzniy defaultPatternComponent Lnet/minecraft/unmapped/C_wwbphpbp;
```suggestion
	FIELD f_yqkmzniy patterns Lnet/minecraft/unmapped/C_wwbphpbp;
```
it's just initialized to the default, it's reassigned from data elsewhere

2024-07-07 04:20 UTC, supersaiyansubtlety commented on mappings/net/minecraft/block/entity/BannerBlockEntity.mapping
> +		ARG 2 dyeColor
```suggestion
		ARG 2 baseColor
```
more specific, and matches the field it's assigned to

2024-07-07 04:20 UTC, supersaiyansubtlety commented on mappings/net/minecraft/enchantment/Enchantments.mapping
> +	METHOD m_fsqdbhms registerEnchantment (Ljava/lang/String;)Lnet/minecraft/unmapped/C_xhhleach;
```suggestion
	METHOD m_fsqdbhms createRegistryKey (Ljava/lang/String;)Lnet/minecraft/unmapped/C_xhhleach;
```
it just creates the key, registration happens in `bootstrap`
In #607 I'll make this consistent for everything with a similar method and a `bootstrap` method called from `VanillaDynamicRegistries`.

2024-07-07 04:20 UTC, supersaiyansubtlety commented on mappings/net/minecraft/enchantment/Enchantments.mapping
> +	METHOD m_zklinuaf registerEnchantment (Lnet/minecraft/unmapped/C_hqoyyfco;Lnet/minecraft/unmapped/C_xhhleach;Lnet/minecraft/unmapped/C_jxtrubuh$C_epmoqirc;)V
```suggestion
	METHOD m_zklinuaf register (Lnet/minecraft/unmapped/C_hqoyyfco;Lnet/minecraft/unmapped/C_xhhleach;Lnet/minecraft/unmapped/C_jxtrubuh$C_epmoqirc;)V
```
I think the params and containing class make it clear that this registers an enchantment

2024-07-07 04:20 UTC, supersaiyansubtlety commented on mappings/net/minecraft/block/dispenser/ProjectileDispenserBehavior.mapping
> +	FIELD f_uupspuna dispenserConfig Lnet/minecraft/unmapped/C_dokwmwgh$C_jscrvllj;
```suggestion
	FIELD f_uupspuna config Lnet/minecraft/unmapped/C_dokwmwgh$C_jscrvllj;
```
I think the containing class makes it clear

2024-07-07 04:24 UTC, supersaiyansubtlety commented on mappings/net/minecraft/enchantment/Enchantments.mapping
> +	METHOD m_fsqdbhms registerEnchantment (Ljava/lang/String;)Lnet/minecraft/unmapped/C_xhhleach;
actually how about
```suggestion
	METHOD m_fsqdbhms createKey (Ljava/lang/String;)Lnet/minecraft/unmapped/C_xhhleach;
```
or
```suggestion
	METHOD m_fsqdbhms keyOf (Ljava/lang/String;)Lnet/minecraft/unmapped/C_xhhleach;
```
(less conventional, but I think it works? maybe we could update conventions?)

2024-07-07 23:03 UTC, ix0rai commented
thanks for the suggestions, i think i'll go with `createKey` for now and we can discuss reevaluating the name

2024-07-08 01:47 UTC, supersaiyansubtlety approved these changes

2024-07-09 01:43 UTC, merged