Some rendering stuff
QuiltMC/quilt-mappings pull request #615
Opened 2024-07-17 06:42 UTC by OroArmor

Also does some font stuff

2024-07-17 22:46 UTC, supersaiyansubtlety requested changes

2024-07-17 22:46 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/font/MultilineText.mapping
> +	METHOD m_gghylmax creat (Lnet/minecraft/unmapped/C_mavozmpp;I[Lnet/minecraft/unmapped/C_rdaqiwdt;)Lnet/minecraft/unmapped/C_ogfbkizf;
```suggestion
	METHOD m_gghylmax create (Lnet/minecraft/unmapped/C_mavozmpp;I[Lnet/minecraft/unmapped/C_rdaqiwdt;)Lnet/minecraft/unmapped/C_ogfbkizf;
```
Another spell-check anomaly?

2024-07-17 22:46 UTC, supersaiyansubtlety commented on mappings/net/minecraft/client/render/GameRenderer.mapping
> +		ARG 0 e
```suggestion
		ARG 0 entity2
```
would be more in line with other lambda params I've seen in QMap, but we should probably clarify what to do for these in a convention.

2024-07-17 23:17 UTC, supersaiyansubtlety approved these changes

2024-07-19 01:44 UTC, ix0rai approved these changes
looks fantastic!

2024-07-19 01:44 UTC, ix0rai commented on mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
> -		ARG 17 alpha
i love param automapping

2024-07-19 01:44 UTC, ix0rai commented on mappings/net/minecraft/client/render/entity/ItemEntityRenderer.mapping
> +	METHOD m_zbaeotrg itemsToDraw (I)I
```suggestion
	METHOD m_zbaeotrg getItemsToDraw (I)I
```

2024-07-19 03:10 UTC, OroArmor commented on mappings/net/minecraft/client/render/entity/ItemEntityRenderer.mapping
> +	METHOD m_zbaeotrg itemsToDraw (I)I
```suggestion
	METHOD m_zbaeotrg getTiledIconsToDraw (I)I
```

2024-07-19 05:59 UTC, IotaBread approved these changes

2024-07-22 03:38 UTC, merged