100% `net/minecraft/world/gen`
QuiltMC/quilt-mappings pull request #616
Opened 2024-07-19 04:19 UTC by OroArmor

I am mentally stable

2024-07-19 10:14 UTC, supersaiyansubtlety requested changes

2024-07-19 10:14 UTC, supersaiyansubtlety commented on mappings/net/minecraft/world/gen/DensityFunctions.mapping
> +		ARG 1 into
```suggestion
		ARG 1 to
```
?

2024-07-19 10:14 UTC, supersaiyansubtlety commented on mappings/net/minecraft/world/gen/chunk/Blender.mapping
> +		ARG 5 l
```suggestion
		ARG 5 chunkPos
```

2024-07-19 10:14 UTC, supersaiyansubtlety commented on mappings/net/minecraft/world/gen/chunk/BlendingData.mapping
> +	METHOD m_pslasnyw zeroIfNegative (I)I
```suggestion
	METHOD m_pslasnyw getMaxWith0 (I)I
```
idak if I like this...
but it should at least have `get`

2024-07-20 22:00 UTC, OroArmor commented on build.gradle
> +				// 'https://fastutil.di.unimi.it/docs/',
```suggestion
				'https://fastutil.di.unimi.it/docs/',
```

2024-07-21 05:06 UTC, supersaiyansubtlety approved these changes

2024-07-21 15:17 UTC, ix0rai approved these changes
looks good! i love how often you just remove mappings for automapped stuff

2024-07-26 23:38 UTC, merged