some mappings for worldrenderer and one picomapping for chunkbuilder
QuiltMC/quilt-mappings pull request #619
Opened 2024-07-24 04:10 UTC by woodiertexas

2024-07-24 04:16 UTC, supersaiyansubtlety requested changes
Since all the `matrix4f` params are along side other `Martrix4f` params, they should have more descriptive names.

2024-07-24 04:16 UTC, supersaiyansubtlety commented on mappings/net/minecraft/unmapped/ChunkBuilder.mapping
please put this in a package

2024-07-24 04:17 UTC, OroArmor requested changes

2024-07-24 04:17 UTC, OroArmor commented on mappings/net/minecraft/unmapped/ChunkBuilder.mapping
> +CLASS net/minecraft/unmapped/C_jnliocmw net/minecraft/unmapped/ChunkBuilder
This isnt really a chunk builder. Its similar but different enough this name is misleading. I would leave this unmapped for now

2024-07-24 04:17 UTC, OroArmor commented on mappings/net/minecraft/client/render/WorldRenderer.mapping
> +	FIELD f_kfsuutjj chunkBuilder Lnet/minecraft/unmapped/C_jnliocmw;
see below comment

2024-07-24 04:36 UTC, OroArmor requested changes
the `matrix4f` parameters are probably the `viewMatrix`. HOWEVER, i would recheck that something didnt change because the order is usually model, view, then projection, but it seems that projection is before view, which is odd.

2024-07-24 04:36 UTC, OroArmor commented on mappings/net/minecraft/client/render/WorldRenderer.mapping
> +	FIELD f_oppequxe blockSounds Ljava/util/Map;
```suggestion
	FIELD f_oppequxe currentSounds Ljava/util/Map;
```

2024-07-24 04:36 UTC, OroArmor commented on mappings/net/minecraft/client/render/WorldRenderer.mapping
> +		ARG 4 defaultParticleType
```suggestion
		ARG 4 particle
```

2024-07-24 04:38 UTC, woodiertexas commented
> the `matrix4f` parameters are probably the `viewMatrix`. HOWEVER, i would recheck that something didnt change because the order is usually model, view, then projection, but it seems that projection is before view, which is odd.

yea, they were `matrix4f2` in the planetarium project in intelliJ

2024-07-24 04:51 UTC, woodiertexas commented
> the `matrix4f` parameters are probably the `viewMatrix`. HOWEVER, i would recheck that something didnt change because the order is usually model, view, then projection, but it seems that projection is before view, which is odd.

in enigma:
![java_AVFFJSPAU1](https://github.com/user-attachments/assets/81b907ed-e86f-4d16-a1de-216d287bdcb4)

in the planetarium project:
![idea64_JGZThcg3bH](https://github.com/user-attachments/assets/f1ad771e-5326-41ac-bc9f-be6e7d1cdc92)

2024-07-25 04:06 UTC, ix0rai requested changes
looks good; besides the `matrix4f` parameters

2024-07-26 21:36 UTC, woodiertexas commented
> looks good; besides the `matrix4f` parameters

so what name would you give those parameters?

2024-07-26 21:56 UTC, OroArmor requested changes
Confirmed by double checking the `Frustrum` constructor mapping

2024-07-26 21:56 UTC, OroArmor commented on mappings/net/minecraft/client/render/WorldRenderer.mapping
> +		ARG 3 matrix4f
```suggestion
		ARG 2 modelViewMatrix
		ARG 3 projectionMatrix
```

2024-07-26 21:56 UTC, OroArmor commented on mappings/net/minecraft/client/render/WorldRenderer.mapping
> +		ARG 7 matrix4f
```suggestion
		ARG 6 modelViewMatrix
		ARG 7 projectionMatrix
```

2024-07-26 21:56 UTC, OroArmor commented on mappings/net/minecraft/client/render/WorldRenderer.mapping
> +		ARG 2 matrix4f
```suggestion
		ARG 1 modelViewMatrix
		ARG 2 projectionMatrix
```

2024-07-26 22:18 UTC, OroArmor approved these changes

2024-07-26 23:47 UTC, supersaiyansubtlety approved these changes

2024-07-27 02:30 UTC, OroArmor requested changes

2024-07-27 02:30 UTC, OroArmor commented on mappings/net/minecraft/client/render/WorldRenderer.mapping
> +	METHOD m_znnjtopn createChunkBuilderDebugLine ()Ljava/lang/String;
```suggestion
	METHOD m_znnjtopn getChunkBuilderDebugString ()Ljava/lang/String;
```
I know I said the previous thing, but I want to match the other functions like this.

2024-07-27 02:30 UTC, OroArmor commented on mappings/net/minecraft/util/math/MathHelper.mapping
> +	METHOD m_saszmoqp magnitude (FFF)F
```suggestion
	METHOD m_saszmoqp lengthSquared (FFF)F
```

2024-07-31 18:33 UTC, OroArmor approved these changes

2024-08-01 01:35 UTC, ix0rai approved these changes

2024-08-01 19:04 UTC, merged