Complete nearly everything in item
QuiltMC/quilt-mappings pull request #623
Opened 2024-07-31 13:26 UTC by diacritics-owo

First Quilt contribution. As per the title, I've written mappings for everything in `item` except for some of `CrossbowItem` and `ItemStack`.

2024-07-31 18:38 UTC, OroArmor requested changes
Some small changes

2024-07-31 18:38 UTC, OroArmor commented on mappings/net/minecraft/item/Item.mapping
> +	METHOD m_bhfktmca getDamage (Lnet/minecraft/unmapped/C_astfners;FLnet/minecraft/unmapped/C_sbxfkpyv;)F
```suggestion
	METHOD m_bhfktmca getAttackDamage (Lnet/minecraft/unmapped/C_astfners;FLnet/minecraft/unmapped/C_sbxfkpyv;)F
```
makes it clearer its not stack damage

2024-07-31 18:38 UTC, OroArmor commented on mappings/net/minecraft/item/CrossbowItem.mapping
> +			ARG 0 loadingSounds
```suggestion
			ARG 0 sounds
```

2024-08-01 01:50 UTC, diacritics-owo commented
I've applied the suggestions! Let me know if there's anything else

2024-08-01 04:20 UTC, supersaiyansubtlety approved these changes
~~why would Mojang do this to us in particular `register("banner_white", "white_banner"...`~~
looks good

2024-08-02 04:20 UTC, OroArmor approved these changes

2024-08-04 04:26 UTC, merged