24w37a ender pearls
QuiltMC/quilt-mappings pull request #638
Opened 2024-09-11 22:22 UTC by EliTheCoder

Some new methods that have to do with ender pearl chunk loading.

This is my first contribution and I have read CONTRIBUTING.md and CONVENTIONS.md but please let me know if anything looks off.

2024-09-11 22:26 UTC, OroArmor approved these changes

2024-09-11 22:36 UTC, supersaiyansubtlety requested changes
looks good, just nitpicks

2024-09-11 22:36 UTC, supersaiyansubtlety commented on mappings/net/minecraft/entity/projectile/thrown/EnderPearlEntity.mapping
> +	FIELD f_hbarhomd chunkLoadTimer J
```suggestion
	FIELD f_hbarhomd chunkLoadTicks J
```

2024-09-11 22:36 UTC, supersaiyansubtlety commented on mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
> +		COMMENT Adds a chunk ender pearl chunk ticket to the ticket manager.
```suggestion
		COMMENT Adds an ender pearl chunk ticket to the ticket manager.
```

2024-09-11 22:42 UTC, EliTheCoder commented
Perfect, thanks

2024-09-11 22:44 UTC, supersaiyansubtlety approved these changes

2024-09-12 03:43 UTC, OroArmor approved these changes

2024-09-12 03:44 UTC, supersaiyansubtlety approved these changes

2024-09-12 23:21 UTC, merged