Add an entry naming lint checker
QuiltMC/quilt-mappings pull request #96
Opened 2022-02-18 21:50 UTC by IotaBread

Checks for proper casing of entries other than fields, and that constructors aren't mapped

2022-02-18 21:56 UTC, OroArmor approved these changes

2022-02-22 10:16 UTC, NoComment1105 requested changes
`WorldGenRegistryDumpReport` is renamed already in #90, #93 and #97

2022-02-22 15:42 UTC, IotaBread commented
> `WorldGenRegistryDumpReport` is renamed already in #90, #93 and #97

It's also here because of the drop invalid mappings task/action, see commit 53da43ab75eae7f99fc600c838054a8a2d60a8e7. I think once any of those prs is merged the change should just be ignored in the others

2022-02-22 15:43 UTC, NoComment1105 commented
Alright sounds good

2022-02-22 15:43 UTC, NoComment1105 approved these changes

2022-02-23 16:28 UTC, merged